[images]
  remote_images = [
    "https://source.unsplash.com/.*", 
    "https://images.unsplash.com/.*", 
    "https://ext.same-assets.com/.*", 
    "https://ugc.same-assets.com/.*"
  ]

[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"

# 启用 Netlify 函数
[functions]
  directory = "netlify/functions"

# 环境变量（需要在 Netlify 控制台中设置）
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NODE_ENV = "production"

# Next.js 插件配置
[[plugins]]
  package = "@netlify/plugin-nextjs"