# Next.js + Netlify 配置
[build]
  command = "npm run build"
  # Next.js 不需要指定 publish 目录，插件会自动处理

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"

# Next.js 插件配置（必须放在文件开头）
[[plugins]]
  package = "@netlify/plugin-nextjs"

# 图片优化设置
[images]
  remote_images = [
    "https://source.unsplash.com/.*", 
    "https://images.unsplash.com/.*", 
    "https://ext.same-assets.com/.*", 
    "https://ugc.same-assets.com/.*"
  ]

# 环境变量配置
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NODE_ENV = "production"